WIP: KP-9134 Add bulk modification tools for Language Bank / FIN-CLARIN as person
CSCfi/Kielipankki-cmdi-bulk-modifier pull request #1
Opened 2024-11-01 13:47 UTC by aajarven

2024-11-27 13:40 UTC, mmatthiesencsc commented on modifiers/lb_modifiers.py
> +            person_surname="FIN-CLARIN", organization_info_str=organization_info_str
To be consistent with lines 132/133:
```suggestion
            person_surname="FIN-CLARIN",
            organization_info_str=organization_info_str,
```

2024-11-27 13:42 UTC, mmatthiesencsc commented on modifiers/lb_modifiers.py
> +        :paran first_name: First name of the edited person
```suggestion
        :param first_name: First name of the edited person
```

2024-11-27 13:51 UTC, mmatthiesencsc commented on conf/example_affiliations.json
I am unsure about the context of  this file, is it used for testing?

2024-11-27 13:52 UTC, mmatthiesencsc requested changes
This code looks very good and extensible. Can't wait to see it in action. I added a few comments/corrections.

2024-11-27 15:08 UTC, aajarven commented on conf/example_affiliations.json
It's an example. It's a lot easier for someone to start using the tool if they have a "template" as opposed to just reading from docs that "the affiliations must be in a json file containing a list of dicts, each dict having keys 'first_name' whose value is the affected person's first name, 'last_name'..."

2024-11-27 15:08 UTC, aajarven commented on modifiers/lb_modifiers.py
> +            person_surname="FIN-CLARIN", organization_info_str=organization_info_str
That's not in our hands: we decided to use Black for Python, and Black does what it pleases. If we want to change individual practices like that, we need to ditch Black altogether and switch to something else.

2024-12-03 07:59 UTC, mmatthiesencsc approved these changes

2024-12-03 10:33 UTC, mmatthiesencsc approved these changes

2024-12-03 12:11 UTC, merged